-- Input is stored in simple table 
-- CREATE TABLE AOC3 (ID NUMBER,VAL VARCHAR2(100));
-- ID is just a sequence to use as as primary key, VAL is the row from input-text.

-- Part 1
WITH SLOPE AS (SELECT ID,SUBSTR(VAL,1+MOD((ROWNUM-1)*3,LENGTH(VAL)),1) AS TREE,VAL FROM AOC3 ORDER BY ID)
SELECT COUNT(1) FROM SLOPE WHERE TREE='#';


-- Part 2 - ugly version
SELECT ROUND(exp(sum(ln(c))),0) FROM (
SELECT COUNT(1) AS C FROM (SELECT ID,SUBSTR(VAL,1+MOD((ROWNUM-1)*1,LENGTH(VAL)),1) AS TREE,VAL FROM AOC3 ORDER BY ID) WHERE TREE='#'
UNION ALL
SELECT COUNT(1) AS C FROM (SELECT ID,SUBSTR(VAL,1+MOD((ROWNUM-1)*3,LENGTH(VAL)),1) AS TREE,VAL FROM AOC3 ORDER BY ID) WHERE TREE='#'
UNION ALL
SELECT COUNT(1) AS C  FROM (SELECT ID,SUBSTR(VAL,1+MOD((ROWNUM-1)*5,LENGTH(VAL)),1) AS TREE,VAL FROM AOC3 ORDER BY ID) WHERE TREE='#'
UNION ALL
SELECT COUNT(1)  AS C FROM (SELECT ID,SUBSTR(VAL,1+MOD((ROWNUM-1)*7,LENGTH(VAL)),1) AS TREE,VAL FROM AOC3 ORDER BY ID) WHERE TREE='#'
UNION ALL
SELECT COUNT(1)  AS C FROM (SELECT ID,SUBSTR(VAL,1+MOD((ROWNUM-1)*1,LENGTH(VAL)),1) AS TREE,VAL FROM (SELECT ID,VAL FROM AOC3 WHERE MOD(ID,2)!=0) ORDER BY ID) WHERE TREE='#'
);


